source 'https://rubygems.org'

gem 'rack', '~> 1.6.0'
gem 'grape', '~> 1.1.0'
gem 'grape-entity', '~> 0.5.1'
gem 'activerecord', '~> 5.0.2', require: 'active_record'
gem 'otr-activerecord', '~> 1.2.1'
gem 'sqlite3'
gem 'rake'
gem 'rspec'
gem 'pry'
gem 'rack-token_auth'
